FROM maven:3.9-eclipse-temurin-21
WORKDIR /app

COPY CommentService/mvnw .
COPY CommentService/.mvn .mvn
COPY CommentService/pom.xml .
COPY AuthenticationService/src ./src

RUN chmod +x mvnw

CMD ["./mvnw", "spring-boot:run"]
