spring.application.name=SessionService
spring.data.redis.host=session-service-redis
spring.data.redis.port=6379
spring.data.redis.password=myStrongPassword
spring.data.redis.timeout=2000

logging.level.com.VoxPopuli.SessionService.controllers=DEBUG
logging.level.com.VoxPopuli.SessionService.services=DEBUG

app.session.timeout:600