FROM maven:3.9-eclipse-temurin-21
WORKDIR /app

COPY AuthenticationService/mvnw .
COPY AuthenticationService/.mvn .mvn
COPY AuthenticationService/pom.xml .

RUN chmod +x mvnw

CMD ["./mvnw", "spring-boot:run"]
